// <auto-generated />
using System;
using ControlSalidas.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlSalidas.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526121504_ciFuncionario")]
    partial class ciFuncionario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("ControlSalidas.API.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSalidas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ci")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasFuera")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Noches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Hospital", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Salidaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Salidaid");

                    b.ToTable("Hospitales");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Salida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("dias")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("fechaLlegada")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("fechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<int>("noches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("salidasCalculadas")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.SalidaFuncionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("funcionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("salidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("funcionarioId");

                    b.HasIndex("salidaId");

                    b.ToTable("SalidaFuncionarios");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Hospital", b =>
                {
                    b.HasOne("ControlSalidas.API.Models.Salida", null)
                        .WithMany("hospital")
                        .HasForeignKey("Salidaid");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.SalidaFuncionario", b =>
                {
                    b.HasOne("ControlSalidas.API.Models.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlSalidas.API.Models.Salida", "salida")
                        .WithMany("Funcionarios")
                        .HasForeignKey("salidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("funcionario");

                    b.Navigation("salida");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Salida", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("hospital");
                });
#pragma warning restore 612, 618
        }
    }
}
