// <auto-generated />
using System;
using ControlSalidas.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlSalidas.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614160557_viaticos")]
    partial class viaticos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("ControlSalidas.Shared.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSalidas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasFuera")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Noches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPernocte")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.HorarioLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("HorarioLaboral");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.HorasSalidaFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HorasExtra")
                        .HasColumnType("REAL");

                    b.Property<double>("HorasNormales")
                        .HasColumnType("REAL");

                    b.Property<int>("SalidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("SalidaId");

                    b.ToTable("HorasSalidaFuncionarios");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hospitales");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.ResumenMensualFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSalidas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasFuera")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HorasExtra")
                        .HasColumnType("REAL");

                    b.Property<double>("HorasNormales")
                        .HasColumnType("REAL");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Noches")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("ResumenesMensuales");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.Salida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaLlegada")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalesIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdFuncionarios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Noches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalidasCalculadas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.SalidaFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImportePernoctes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pernoctes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalidaFuncionarios");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.Viatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Viaticos");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.HorarioLaboral", b =>
                {
                    b.HasOne("ControlSalidas.Shared.Models.Funcionario", null)
                        .WithMany("Horarios")
                        .HasForeignKey("FuncionarioId");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.HorasSalidaFuncionario", b =>
                {
                    b.HasOne("ControlSalidas.Shared.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlSalidas.Shared.Models.Salida", "Salida")
                        .WithMany()
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.ResumenMensualFuncionario", b =>
                {
                    b.HasOne("ControlSalidas.Shared.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("ControlSalidas.Shared.Models.Funcionario", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
