// <auto-generated />
using System;
using ControlSalidas.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlSalidas.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522003520_comienzoSalidasNuevas")]
    partial class comienzoSalidasNuevas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("ControlSalidas.API.Models.Funcionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidadSalidas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("diasFuera")
                        .HasColumnType("INTEGER");

                    b.Property<int>("noches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Hospital", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Hospitales");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Salida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("dias")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("fechaLlegada")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("fechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<int>("funcionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("noches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("salidasCalculadas")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("hospitalId");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.SalidaFuncionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("funcionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("salidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("funcionarioId");

                    b.HasIndex("salidaId");

                    b.ToTable("SalidaFuncionario");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Salida", b =>
                {
                    b.HasOne("ControlSalidas.API.Models.Hospital", "hospital")
                        .WithMany()
                        .HasForeignKey("hospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hospital");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.SalidaFuncionario", b =>
                {
                    b.HasOne("ControlSalidas.API.Models.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlSalidas.API.Models.Salida", "salida")
                        .WithMany("Funcionarios")
                        .HasForeignKey("salidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("funcionario");

                    b.Navigation("salida");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Salida", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
