// <auto-generated />
using System;
using ControlSalidas.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlSalidas.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604120518_HorariosLaboralesEnSalida")]
    partial class HorariosLaboralesEnSalida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("ControlSalidas.API.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSalidas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasFuera")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("HorarioLaboralEntrada")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HorarioLaboralSalida")
                        .HasColumnType("TEXT");

                    b.Property<int>("Noches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hospitales");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.Salida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dias")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaLlegada")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalesIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdFuncionarios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Noches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalidasCalculadas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("ControlSalidas.API.Models.SalidaFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalidaFuncionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
